# Install and run clang-tidy
name: Clang-tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clang-tidy
      run: |
          sudo apt-get install -y clang-tidy-9
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-9 100
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: Run clang-tidy
      run: shopt -s globstar extglob failglob && ls **/*.@(h|H|hh|hpp|hxx|h++|c|C|cc|cpp|cxx|c++) | grep -v build | tr '\n' ' ' | xargs clang-tidy
